### ISSUE TITLE
Correct epsg reference

### ISSUE THREAD

**Issue by trosendal** [trosendal/svis#1]
https://github.com/trosendal/svis/blob/b125d619c3e9a599dc56172456f2ae823c56fda3/R/read_data.R#L49

Should this function be EPSG:4326 or EPSG:4327 EPSG:4328.... They all read as though they are unprojected WGS84. I'm confused :)

**Comment by hykim3594** [comment]
It should be EPSG:4326 which is the world standard. EPSG:4327 is for 3D WGS84 and EPSG:4326 is for 2D WGS84. 

EPSG:4328 uses geocentric latitude and EPSG:4326 uses geodetic latitude. I don't know exactly how they are different..

**Comment by trosendal** [comment]
OK, can you change that at https://github.com/trosendal/svis/blob/master/R/read_data.R#L62

It should be a similar construction to 
https://github.com/trosendal/svis/blob/master/R/read_data.R#L44
and https://github.com/trosendal/svis/blob/master/R/read_data.R#L53

**Comment by trosendal** [comment]
Here are the steps to contribute:
1. Clone the project in R studio.
2. Change the code at line 62
3. Save the file, and commit the change
4. push to github
:-)
