### ISSUE TITLE
sample data ASF

### ISSUE THREAD

**Issue by trosendal** [trosendal/svis#3]
Add sample data for ASF testing of wild pigs

This can be added to the inst/extdata directory preferably in tab separated format.

**Comment by trosendal** [comment]
Then we would write a method to read that sample data

**Comment by hykim3594** [comment]
I added the sample data. Daily updated files can be obtained from the directory T:\Falkenrapporter.

**Comment by trosendal** [comment]
I actually removed it again because I saw that it had some information that we can't make public. We can have a look at how to clean that up

**Comment by trosendal** [comment]
@hykim3594 I added the data back in a cleaned form but I'm unable to read it. The function here:

https://github.com/trosendal/svis/blob/master/R/read_data.R#L66

doesn't work. See the test that I have commented out:

https://github.com/trosendal/svis/blob/master/tests/test1.R#L109

I don't have a copy of the original data, so I'm unsure if I broke it when I modified it, or if the original data also results in this error. Can you investigate?

**Comment by hykim3594** [comment]
I changed the data read function from read.table to read.csv and added tab separator. It seems to be working.

**Comment by trosendal** [comment]
wierd. I'll have to study the difference between those two functions. I always use read.table for tab separated stuff. Perhaps I'll rethink that. Thanks.
